---
kind: pipeline
name: default

steps:
  - name: check
    image: guangie88/rustfmt-clippy:1.51.0-stable
    commands:
      - cargo check --workspace
  - name: lint
    image: guangie88/rustfmt-clippy:1.51.0-stable
    commands:
      - cargo fmt --all -- --check
      - cargo clippy -- -D warnings
  - name: test
    image: guangie88/rustfmt-clippy:1.51.0-stable
    commands:
      - cargo test --verbose --all
  - name: package
    image: guangie88/rustfmt-clippy:1.51.0-stable
    depends_on: [test, lint]
    commands:
      - cargo build --verbose --all
