[package]
name = 'actix-demo'
version = '0.1.0'
authors = ['Rohan Sircar <rohansircar@tuta.io>']
edition = '2021'

[dependencies]
tokio = { version = "1.21.2", features = ["sync", "macros", "process"] }
anyhow = "1.0.66"
async-recursion = "1.0.0"
diesel-derive-enum = { version = "1", features = ["postgres"] }
actix-ws = "0.2.5"
actix-web = "4.2.1"
actix-service = "2.0.0"
actix-files = "0.6.2"
actix-http = "3.2.2"
jwt-simple = "0.11.2"
bytes = "1.0.1"
futures = "0.3.14"
serde_json = "1.0.64"
dotenv = "0.15.0"
r2d2 = "0.8.9"
actix-web-httpauth = "0.8.0"
rand = "0.8.3"
nanoid = "0.4.0"
bcrypt = "0.13.0"
timeago = "0.3.0"
regex = "1.4.5"
lazy_static = "1.4.0"
lazy-regex = "2.3.1"
custom_error = "1.9.2"
derive-new = "0.5.9"
diesel_migrations = "1.4.0"
actix-threadpool = "0.3.3"
envy = "0.4"
tracing = { version = "0.1" }
tracing-log = "0.1.2"
async-trait = "0.1.58"
futures-util = "0.3.25"
tracing-subscriber = { version = "0.3.16", features = [
    "fmt",
    "registry",
    "env-filter",
] }
tracing-futures = "0.2.5"
tracing-actix-web = "0.6.2"
tracing-bunyan-formatter = "0.3.4"
diesel-tracing = { version = "0.1.6", features = ["postgres"] }

diesel-derive-newtype = "1.0.0"
derive_more = "0.99.13"
tracing-appender = "0.2.2"
actix-rt = "2.7.0"
actix-web-grants = "3.0.1"
do-notation = "0.1.3"
url = { version = "1.4.0" }
redis = { version = "0.22.1", features = [
    "tokio-comp",
    "json",
    "connection-manager",
] }
process-stream = "0.4.1"
once_cell = "1.16.0"

[dependencies.validators]
version = "0.24.3"
features = ["serde"]

[dependencies.validators-derive]
version = "0.24.1"
features = ["serde"]

[dependencies.build-info]
version = "0.0.29"
features = ['runtime', 'serde']

[dependencies.serde]
version = "1.0.125"
features = ['derive']

[dependencies.diesel]
version = "1.4.8"
features = ['r2d2', 'chrono', 'postgres', 'uuidv07']

[dependencies.uuid]
version = "0.8.2"
features = ['serde', 'v4']

[dependencies.chrono]
version = "0.4.19"
features = ['serde']

[dev-dependencies]
actix-codec = "0.5.0"
actix-test = "0.1.0"
awc = "3.0.1"
bytestring = { version = "1.2.0", features = ["serde"] }
derive_builder = "0.12.0"
testcontainers = { git = "https://github.com/testcontainers/testcontainers-rs/" } # testcontainers = "0.14.0"
tokio-postgres = "0.7.7"

[build-dependencies]
build-info-build = "0.0.29"
