[package]
name = 'actix-demo'
version = '0.1.0'
authors = ['Rohan Sircar <rohansircar@tuta.io>']
edition = '2018'

[dependencies]
actix-web = '2'
actix-rt = '1'
actix-service = '1.0.5'
actix-files = '0.2.1'
bytes = '0.5.4'
futures = '0.3.4'
log = '0.4.8'
env_logger = '0.7'
serde_json = '1.0.52'
json = '0.12.4'
listenfd = '0.3.3'
dotenv = '0.15'
r2d2 = '0.8.8'
validator = '0.10.0'
validator_derive = '0.10'
jsonwebtoken = '7'
actix-identity = '0.2.1'
actix-web-httpauth = '0.4.1'
actix-http = '1.0.1'
rand = '0.7.3'
nanoid = '0.3.0'
bcrypt = '0.7'
timeago = '0.2.1'
comp = '0.2.1'
regex = '1.3.7'
lazy_static = '1.4.0'
lazy-regex = '0.1.2'
custom_error = '1.7.1'

[dependencies.serde]
version = '1.0.106'
features = ['derive']

[dependencies.yarte]
version = '0.9.0'
features = ['html-min']

[dependencies.diesel]
version = '1.4.4'
features = [
    'sqlite',
    'r2d2',
    'chrono',
]

[dependencies.uuid]
version = '0.8'
features = [
    'serde',
    'v4',
]

[dependencies.rusqlite]
version = '0.21.0'
features = ['bundled']

[dependencies.chrono]
version = '0.4.11'
features = ['serde']
[build-dependencies.yarte_helpers]
version = '0.9.0'
default-features = false
features = ['config']
