[package]
name = 'actix-demo'
version = '0.1.0'
authors = ['Rohan Sircar <rohansircar@tuta.io>']
edition = '2018'

[dependencies]
actix-web = "2.0.0"
actix-rt = "1.1.1"
actix-service = "1.0.6"
actix-files = "0.2.2"
bytes = "0.5.6"
futures = "0.3.5"
log = "0.4.11"
env_logger = "0.7.1"
serde_json = "1.0.57"
json = "0.12.4"
listenfd = "0.3.3"
dotenv = "0.15.0"
r2d2 = "0.8.9"
validator = "0.10.1"
validator_derive = "0.10.1"
jsonwebtoken = "7.2.0"
actix-identity = "0.2.1"
actix-web-httpauth = "0.4.2"
rand = "0.7.3"
nanoid = "0.3.0"
bcrypt = "0.8.2"
timeago = "0.2.1"
comp = "0.2.1"
regex = "1.3.9"
lazy_static = "1.4.0"
lazy-regex = "0.1.4"
custom_error = "1.7.1"
derive-new = "0.5.8"
diesel_migrations = "1.4.0"
actix-threadpool = "0.3.3"

[dependencies.serde]
version = "1.0.115"
features = ['derive']

# [dependencies.yarte]
# version = '0.9.0'
# features = ['html-min']

[dependencies.diesel]
version = "1.4.5"
features = [
    'sqlite',
    'r2d2',
    'chrono',
]

[dependencies.uuid]
version = "0.8.1"
features = [
    'serde',
    'v4',
]

[dependencies.rusqlite]
version = "0.23.1"
features = ['bundled']

[dependencies.chrono]
version = "0.4.15"
features = ['serde']
# [build-dependencies.yarte_helpers]
# version = '0.9.0'
# default-features = false
# features = ['config']
