[package]
name = 'actix-demo'
version = '0.1.0'
authors = ['Rohan Sircar <rohansircar@tuta.io>']
edition = '2018'

[dependencies]
actix-web = "3.3.2"
actix-service = "2.0.0"
actix-files = "0.5.0"
actix-http = "2.2.0"
bytes = "1.0.1"
futures = "0.3.14"
serde_json = "1.0.64"
# json = "0.12.4"
# listenfd = "0.3.3"
dotenv = "0.15.0"
r2d2 = "0.8.9"
validator = "0.13.0"
validator_derive = "0.13.0"
# jsonwebtoken = "7.2.0"
actix-identity = "0.3.1"
actix-web-httpauth = "0.5.1"
rand = "0.8.3"
nanoid = "0.4.0"
bcrypt = "0.9.0"
timeago = "0.3.0"
# comp = "0.2.1"
regex = "1.4.5"
lazy_static = "1.4.0"
lazy-regex = "0.1.4"
custom_error = "1.9.2"
derive-new = "0.5.9"
diesel_migrations = "1.4.0"
actix-threadpool = "0.3.3"
envy = "0.4"
tracing = { version = "0.1" }
tracing-log = "0.1.2"
tracing-subscriber = { version = "0.2.18", features = ["fmt", "registry", "env-filter"] }
tracing-futures = "0.2.5"
tracing-actix-web = "0.2.1"
tracing-bunyan-formatter = "0.2.4"

[dependencies.build-info]
version = "=0.0.23"
features = ['runtime', 'serde']

[dependencies.serde]
version = "1.0.125"
features = ['derive']

[dependencies.diesel]
version = "1.4.5"
features = ['sqlite', 'r2d2', 'chrono']

[dependencies.uuid]
version = "0.8.2"
features = ['serde', 'v4']

[dependencies.rusqlite]
version = "0.23.1"
features = ['bundled']

[dependencies.chrono]
version = "0.4.19"
features = ['serde']

[dev-dependencies]
actix-rt = "1.1.1"

[build-dependencies]
build-info-build = "=0.0.23"
