[package]
name = "actix-demo"
version = "0.1.0"
authors = ["Rohan Sircar <rohansircar@tuta.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2"
actix-rt = "1"
actix-service = "1.0.5"
actix-files = "0.2.1"

bytes = "0.5.4"
futures = "0.3.4"
log = "0.4.8"
env_logger = "0.7"

serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.52"
json = "0.12.4"

yarte = { version = "0.8.3", features = ["html-min"]  }

listenfd = "0.3.3"

diesel = { version = "1.4.4", features = ["sqlite", "r2d2"] }
dotenv = "0.15"
r2d2 = "0.8.8"
uuid = { version = "0.8", features = ["serde", "v4"] }
validator = "0.10.0"
jsonwebtoken = "7"
actix-identity = "0.2.1"
actix-web-httpauth = "0.4.1"
actix-http = "1.0.1"
rand = "0.7.3"
nanoid = "0.3.0"

[build-dependencies.yarte_helpers]
version = "0.8"
default-features = false
features = ["config"]