[package]
name = 'actix-demo'
version = '0.1.0'
authors = ['Rohan Sircar <rohansircar@protonmail.com>']
edition = '2021'

[dependencies]
actix-files = "0.6.2"
actix-http = "3.2.2"
actix-extensible-rate-limit = { version = "0.4.0", features = ["redis"] }
actix-rt = "2.7.0"
actix-service = "2.0.0"
actix-threadpool = "0.3.3"
actix-web = "4.9.0"
actix-web-grants = "3.0.1"
actix-web-httpauth = "0.8.0"
actix-ws = "0.2.5"
anyhow = "1.0.66"
async-recursion = "1.0.0"
async-trait = "0.1.58"
bcrypt = "0.13.0"
bytes = "1.0.1"
chrono = { version = "0.4.19", features = ['serde'] }
custom_error = "1.9.2"
diesel = { version = "2.1.0", features = [
    'r2d2',
    'chrono',
    'postgres',
    'uuid',
] }
diesel-derive-enum = { version = "2.1.0", features = ["postgres"] }
diesel_migrations = "2.1.0"
diesel-tracing = { version = "0.3.1", features = ["postgres", "r2d2"] }
do-notation = "0.1.3"
dotenv = "0.15.0"
dotenvy = "0.15"
envy = "0.4"
env_logger = "0.11.6"
futures = "0.3.14"
futures-util = "0.3.25"
jwt-simple = "0.11.2"
lazy-regex = "2.3.1"
lazy_static = "1.4.0"
log = "0.4.25"
nanoid = "0.4.0"
once_cell = "1.16.0"
process-stream = "0.4.1"
rand = "0.8.3"
regex = "1.4.5"
redis = { version = "0.26.0", features = [
    "tokio-comp",
    "json",
    "connection-manager",
] }
r2d2 = { version = "0.8" }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.64"
timeago = "0.3.0"
tokio = { version = "1.43.0", features = ["full"] }
tracing = { version = "0.1.41" }
tracing-actix-web = "0.7.15"
tracing-appender = "0.2.2"
tracing-bunyan-formatter = "0.3.4"
tracing-futures = "0.2.5"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.16", features = [
    "fmt",
    "registry",
    "env-filter",
] }
uuid = { version = "1.13.1", features = ["v4", "serde"] }
url = { version = "1.4.0" }
validators = { version = "0.24.3", features = ["serde"] }
validators-derive = { version = "0.24.1", features = ["serde"] }

[dev-dependencies]
actix-codec = "0.5.0"
actix-test = "0.1.0"
awc = "3.5.1"
bytestring = { version = "1.2.0", features = ["serde"] }
derive_builder = "0.12.0"
testcontainers = "0.23.2"
testcontainers-modules = { version = "0.11.6", features = [
    "postgres",
    "redis",
] }
tokio-postgres = "0.7.7"

[build-dependencies]
build-info-build = "0.0.29"

[dependencies.build-info]
version = "0.0.29"
features = ['runtime', 'serde']

[dependencies.derive-new]
version = "0.5.9"

[dependencies.diesel-derive-newtype]
version = "2.1.2"

[dependencies.derive_more]
version = "0.99.13"
