services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - metrics-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./docs/enhancements/grafana_dashboard.json:/etc/grafana/provisioning/dashboards/api_metrics.json
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - metrics-net
    depends_on:
      - prometheus

volumes:
  grafana-storage:


networks:
  metrics-net:
